/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/eoPDsKEBVE1
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";

import { useState, useEffect } from "react";
import { Input } from "@/components/ui/input";
import { Platform } from "@prisma/client";

interface AutocompleteProps {
  defaultValue: string;
  options: {
    id: string;
    name: string;
    platforms: Platform[];
    coverImage: string;
  }[];
}

export function Autocomplete({ defaultValue, options }: AutocompleteProps) {
  const [searchTerm, setSearchTerm] = useState(defaultValue);
  // useEffect(() => {
  //   const fetchSearchResults = () => {
  //     if (searchTerm.trim() === "") {
  //       setSearchResults([]);
  //       return;
  //     }
  //     const results = [
  //       {
  //         id: 1,
  //         title: "Tailwind CSS",
  //         description:
  //           "A utility-first CSS framework for rapidly building custom designs.",
  //       },
  //       {
  //         id: 2,
  //         title: "React",
  //         description: "A JavaScript library for building user interfaces.",
  //       },
  //       {
  //         id: 3,
  //         title: "Next.js",
  //         description:
  //           "A React framework for building server-rendered applications.",
  //       },
  //       {
  //         id: 4,
  //         title: "Vercel",
  //         description:
  //           "A platform for frontend frameworks and static sites, built to integrate with your headless content.",
  //       },
  //       {
  //         id: 5,
  //         title: "Shadcn UI",
  //         description:
  //           "A collection of beautifully designed, accessible and customizable components for your React applications.",
  //       },
  //     ].filter((result) =>
  //       result.title.toLowerCase().includes(searchTerm.toLowerCase())
  //     );
  //     setSearchResults(results);
  //   };
  //   fetchSearchResults();
  // }, [searchTerm]);

  return (
    <div className="relative w-full max-w-md">
      <Input
        type="search"
        placeholder="Search..."
        value={searchTerm}
        defaultValue={defaultValue}
        onChange={(e) => setSearchTerm(e.target.value)}
        className="w-full rounded-md border border-input bg-background px-4 py-2 text-foreground shadow-sm focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary-foreground"
        autoFocus
      />
      {options.length > 0 && (
        <ul className="absolute z-10 mt-2 max-h-[300px] w-full overflow-auto rounded-md border border-input bg-background shadow-lg">
          {options.map(({ id, platforms, coverImage, name }) => (
            <li key={id} className="cursor-pointer px-4 py-2 hover:bg-muted">
              <div className="font-medium">{name}</div>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
