/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/PuUvskdzNv6
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";

export function Welcome() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32 bg-gradient-to-r from-[#6366F1] to-[#8B5CF6]">
      <div className="grid container items-center justify-center gap-8 px-4 text-center md:px-6 lg:grid-cols-2 lg:text-left">
        <div className="space-y-4">
          <h1 className="text-4xl font-bold tracking-tighter text-white sm:text-5xl md:text-6xl">
            Welcome to PlayRes
          </h1>
          <p className="max-w-[700px] text-lg text-white/90 md:text-xl/relaxed">
            Your go-to place for detailed information on how the latest games
            perform on current-generation consoles.
          </p>
          <Link
            href="/games"
            className="inline-flex h-10 items-center justify-center rounded-md bg-white px-8 text-sm font-medium text-[#6366F1] shadow transition-colors hover:bg-white/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
            prefetch={false}
          >
            Explore Games
          </Link>
        </div>
        <div>
          <img
            src="/placeholder.svg"
            alt="Game Database"
            width="600"
            height="400"
            className="mx-auto rounded-lg object-cover shadow-lg"
            style={{ aspectRatio: "600/400", objectFit: "cover" }}
          />
        </div>
      </div>
    </section>
  );
}
