/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/pRFXt3EAWkB
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardContent } from "@/components/ui/card";
import Link from "next/link";
import Image from "next/image";
import { Platform } from "@prisma/client";
import { Badge } from "../ui/badge";

interface GameCardProps {
  id: string;
  name: string;
  platforms: Platform[];
  img: string;
  tags: string[];
}

export default function GameCard({
  img,
  platforms,
  name,
  id,
  tags,
}: GameCardProps) {
  return (
    <Card className="w-full max-w-md rounded-lg overflow-hidden shadow-lg transition-transform duration-300 ease-in-out hover:-translate-y-2 hover:shadow-xl">
      <Link href={`/games/${id}`}>
        <CardContent className="grid grid-cols-2 p-0">
          <div className="h-full w-full">
            <img
              src={img}
              alt={name}
              className="object-fit w-full h-full max-h-[250px]"
            />
          </div>
          <div className=" p-4 bg-background">
            {/* Game name */}
            <div className="break-words">
              <h3 className="text-xl font-bold">{name}</h3>
            </div>
            {/* Platforms */}
            <div className="flex gap-2">
              {platforms.map(({ id, logo, name }) => (
                <Image key={id} src={logo} alt={name} width={20} height={20} />
              ))}
            </div>
            {/* Performance tags */}
            <div className="mt-2">
              {tags.map((tag) => (
                <Badge
                  key={tag}
                  className="px-2 mr-2 mb-2 py-1 text-xs font-semibold text-white bg-primary rounded"
                >
                  {tag}
                </Badge>
              ))}
            </div>
          </div>
        </CardContent>
      </Link>
    </Card>
  );
}
